# NLP with CNN


*   This model using `kashgari` package, which needs to use "tensorflow 2.5.0".
*   The accuracy for training set can go to 98%.
*   The final score at Kaggle is 96.291%.



In [2]:
import subprocess
import sys

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

In [3]:
install("tensorflow_addons==0.13.0")

In [4]:
install("tensorflow==2.5.0")

In [5]:
install("kashgari")

In [6]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import re
from sklearn import model_selection, preprocessing, linear_model, naive_bayes, metrics, svm
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn import decomposition, ensemble

import pandas, xgboost, numpy, textblob, string
from keras.preprocessing import text, sequence
from keras import layers, models, optimizers

Using TensorFlow backend.


In [30]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

df_train = pd.read_csv (r'/content/train_features.csv')
df_test = pd.read_csv (r'/content/test_features.csv')
df_label = pd.read_csv (r'/content/train_labels.csv')

train_y_all = np.array(df_label['labels'], dtype = "uint32").tolist()
def Kmers_funct(seq, size=6):
   return [seq[x:x+size].lower() for x in range(len(seq) - size + 1)]
#convert our training data sequences into short overlapping k-mers of length 6. 
dna = df_train['dna']
train_x_all= dna.apply(lambda x: Kmers_funct(x)).to_list()


In [9]:
from sklearn.model_selection import train_test_split

In [32]:
train_x, valid_x, train_y, valid_y = train_test_split(
    train_x_all, train_y_all, test_size=0.2, random_state=8)

In [35]:
from kashgari.tasks.classification import CNN_Model	

model = CNN_Model()
model.fit(train_x, train_y, valid_x, valid_y, epochs=5)

Preparing text vocab dict: 100%|██████████| 2582/2582 [00:00<00:00, 5220.55it/s]
2021-09-26 01:05:04,638 [DEBUG] kashgari - --- Build vocab dict finished, Total: 6092 ---
2021-09-26 01:05:04,640 [DEBUG] kashgari - Top-10: ['[PAD]', '[UNK]', '[CLS]', '[SEP]', '------', 'ttatta', 'tttatt', 'tttttt', 'ttttat', 'aatttt']
Calculating sequence length: 100%|██████████| 2582/2582 [00:00<00:00, 367083.35it/s]
2021-09-26 01:05:04,757 [DEBUG] kashgari - Calculated sequence length = 656
2021-09-26 01:05:04,803 [DEBUG] kashgari - Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           [(None, None)]            0         
_________________________________________________________________
layer_embedding (Embedding)  (None, None, 100)         609200    
_________________________________________________________________
conv1d_1 (Conv1D)            (None, None, 128)         64128    

Epoch 1/5
161/161 [==============================] - 65s 402ms/step - loss: 6.6172 - accuracy: 0.0396 - val_loss: 5.3679 - val_accuracy: 0.1598
Epoch 2/5
161/161 [==============================] - 64s 400ms/step - loss: 1.8608 - accuracy: 0.6981 - val_loss: 0.4883 - val_accuracy: 0.9164
Epoch 3/5
161/161 [==============================] - 64s 398ms/step - loss: 0.1636 - accuracy: 0.9658 - val_loss: 0.2308 - val_accuracy: 0.9512
Epoch 4/5
161/161 [==============================] - 64s 400ms/step - loss: 0.0656 - accuracy: 0.9858 - val_loss: 0.1435 - val_accuracy: 0.9715
Epoch 5/5
161/161 [==============================] - 64s 400ms/step - loss: 0.0386 - accuracy: 0.9910 - val_loss: 0.1416 - val_accuracy: 0.9707


In [ ]:
# Model data will save to `saved_ner_model` folder
model.save('saved_cnn_model')

# Load saved model
loaded_model = CNN_Model.load_model('saved_cnn_model')

2021-09-24 16:08:10,322 [INFO] kashgari - model saved to /content/saved_cnn_model


In [ ]:
loaded_model = CNN_Model.load_model('saved_cnn_model')
loaded_model.compile_model()
model.fit(train_x, train_y, valid_x, valid_y, epochs = 5)

2021-09-24 16:08:11,752 [DEBUG] kashgari - Model: "model_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           [(None, None)]            0         
_________________________________________________________________
layer_embedding (Embedding)  (None, None, 100)         609200    
_________________________________________________________________
conv1d_6 (Conv1D)            (None, None, 128)         64128     
_________________________________________________________________
global_max_pooling1d_5 (Glob (None, 128)               0         
_________________________________________________________________
dense_7 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_8 (Dense)              (None, 1202)              78130     
_________________________________________________________________
activation_4 (Ac

Epoch 1/5
161/161 [==============================] - 64s 395ms/step - loss: 0.0366 - accuracy: 0.9914 - val_loss: 0.1160 - val_accuracy: 0.9789
Epoch 2/5
161/161 [==============================] - 63s 395ms/step - loss: 0.0280 - accuracy: 0.9923 - val_loss: 0.1151 - val_accuracy: 0.9805
Epoch 3/5
161/161 [==============================] - 64s 396ms/step - loss: 0.0207 - accuracy: 0.9943 - val_loss: 0.1187 - val_accuracy: 0.9777
Epoch 4/5
161/161 [==============================] - 64s 395ms/step - loss: 0.0179 - accuracy: 0.9952 - val_loss: 0.1163 - val_accuracy: 0.9805
Epoch 5/5
161/161 [==============================] - 64s 395ms/step - loss: 0.0156 - accuracy: 0.9955 - val_loss: 0.1102 - val_accuracy: 0.9828


In [ ]:
model.fit(train_x, train_y, valid_x, valid_y, epochs = 5)

2021-09-24 16:14:25,488 [DEBUG] kashgari - Model: "model_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           [(None, None)]            0         
_________________________________________________________________
layer_embedding (Embedding)  (None, None, 100)         609200    
_________________________________________________________________
conv1d_6 (Conv1D)            (None, None, 128)         64128     
_________________________________________________________________
global_max_pooling1d_5 (Glob (None, 128)               0         
_________________________________________________________________
dense_7 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_8 (Dense)              (None, 1202)              78130     
_________________________________________________________________
activation_4 (Ac

Epoch 1/5
161/161 [==============================] - 64s 395ms/step - loss: 0.0135 - accuracy: 0.9960 - val_loss: 0.1082 - val_accuracy: 0.9832
Epoch 2/5
161/161 [==============================] - 63s 394ms/step - loss: 0.0121 - accuracy: 0.9967 - val_loss: 0.1093 - val_accuracy: 0.9828
Epoch 3/5
161/161 [==============================] - 63s 392ms/step - loss: 0.0112 - accuracy: 0.9965 - val_loss: 0.1172 - val_accuracy: 0.9809
Epoch 4/5
161/161 [==============================] - 64s 399ms/step - loss: 0.0105 - accuracy: 0.9973 - val_loss: 0.1091 - val_accuracy: 0.9812
Epoch 5/5
161/161 [==============================] - 65s 403ms/step - loss: 0.0092 - accuracy: 0.9971 - val_loss: 0.1100 - val_accuracy: 0.9820


In [ ]:
# full training
model = CNN_Model()
model.fit(train_x_all, train_y_all, epochs = 10)

Preparing text vocab dict: 100%|██████████| 12906/12906 [00:01<00:00, 6606.46it/s]
2021-09-24 16:20:03,691 [DEBUG] kashgari - --- Build vocab dict finished, Total: 6092 ---
2021-09-24 16:20:03,694 [DEBUG] kashgari - Top-10: ['[PAD]', '[UNK]', '[CLS]', '[SEP]', '------', 'TTATTA', 'TTTATT', 'TTTTTT', 'TTTTAT', 'AATTTT']
Calculating sequence length: 100%|██████████| 12906/12906 [00:00<00:00, 1162397.46it/s]
2021-09-24 16:20:03,763 [DEBUG] kashgari - Calculated sequence length = 656
2021-09-24 16:20:03,804 [DEBUG] kashgari - Model: "model_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           [(None, None)]            0         
_________________________________________________________________
layer_embedding (Embedding)  (None, None, 100)         609200    
_________________________________________________________________
conv1d_7 (Conv1D)            (None, None, 128)         641

Epoch 1/10
201/201 [==============================] - 77s 382ms/step - loss: 6.2417 - accuracy: 0.0797
Epoch 2/10
201/201 [==============================] - 77s 384ms/step - loss: 0.8550 - accuracy: 0.8542
Epoch 3/10
201/201 [==============================] - 77s 384ms/step - loss: 0.1075 - accuracy: 0.9770
Epoch 4/10
201/201 [==============================] - 77s 383ms/step - loss: 0.0531 - accuracy: 0.9879
Epoch 5/10
201/201 [==============================] - 76s 380ms/step - loss: 0.0326 - accuracy: 0.9927
Epoch 6/10
201/201 [==============================] - 77s 384ms/step - loss: 0.0297 - accuracy: 0.9927
Epoch 7/10
201/201 [==============================] - 77s 384ms/step - loss: 0.0187 - accuracy: 0.9958
Epoch 8/10
201/201 [==============================] - 76s 379ms/step - loss: 0.0201 - accuracy: 0.9949
Epoch 9/10
201/201 [==============================] - 76s 379ms/step - loss: 0.0163 - accuracy: 0.9950
Epoch 10/10
201/201 [==============================] - 77s 382ms/step - l

In [ ]:
pred = model.predict(test_x)

2021-09-24 17:13:41,842 [WARNING] kashgari - Sequence length is None, will use the max length of the samples, which is 1055
2021-09-24 17:13:44,463 [DEBUG] kashgari - predict input shape (8306, 1055) x: 
[[   2  112  147 ...    0    0    0]
 [   2 1528 1879 ...    0    0    0]
 [   2  110  188 ...    0    0    0]
 ...
 [   2  118  468 ...    0    0    0]
 [   2  110  188 ...    0    0    0]
 [   2  907 2392 ...    0    0    0]]
2021-09-24 17:14:05,066 [DEBUG] kashgari - predict output shape (8306, 1202)
2021-09-24 17:14:05,085 [DEBUG] kashgari - predict output argmax: [1157   11   52 ... 1126  817  714]


In [ ]:
np.shape(pred)

(8306,)

In [ ]:
with open('pred_cnn_ww_2.txt', 'w') as f:
    for item in pred:
        f.write("%s\n" % item)